# Generated by Django 2.2.7 on 2019-12-05 18:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição Breve')),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_fim', models.DateField(verbose_name='Data Fim')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Proponent')),
            ],
        ),
    ]
