# Generated by Django 2.2.7 on 2019-12-09 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20191206_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='data_fim',
        ),
    ]
