# Generated by Django 2.2.7 on 2019-12-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20191209_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='data_fim',
            field=models.DateField(null=True, verbose_name='Data Fim'),
        ),
    ]
